### ISSUE TITLE
Некорректная работа на стороне Яндекс Метрики

### ISSUE THREAD

**Issue by x100x-dev** [hcodes/server_yametrika_nodejs#12]
Яндекс Метрика стала неверно интерпретировать данные, получаемые от server_yametrika_nodejs.

Все запросы приходят с ip адреса самого сервера, а не с ip адресов пользователей.
При этом сами данные передаются верно: x-real-ip который посылается на сервера метрики указывает именно на ip адрес пользователя.
В статистике Яндекс Метрики все пользователи имеют ip сервера. Без исключений.

Данная проблема возникла без каких либо изменений на стороне сервера.

**Comment by hcodes** [comment]
Нужно в поддержку Метрики обращаться.

**Comment by x100x-dev** [comment]
Вот ответ от Метрики:
Дело в том, что техническая поддержка не занимается поддержкой плагинов и скриптов, поэтому, к сожалению, мы не можем вам помочь с ответом на данный вопрос.
Рекомендуем обратится к разработчику скрипта.

**Comment by hcodes** [comment]
Нашёл, с 12 октября в отчёте «География» некорректные данные. Поддержки нужно было объяснить, что отвалился проброс HTTP-заголовка x-real-ip в Метрику. Попробую сам написать.

**Comment by x100x-dev** [comment]
Я им как раз и писал про x-real-ip. 
Пытался достучаться до кого-то более компетентного, но получил вот такой ответ:
По информации, представленной нашими техническими специалистами, Яндекс.Метрика официально не поддерживает работу на серверной стороне. Счетчик Яндекс.Метрики предполагает работу только на клиентской стороне в момент визита пользователя на сайт.
Указанное решение не является разработкой компании Яндекс — это какое-то стороннее решение. Мы не можем каким-либо образом отвечать за его работоспособность.
Единственный вариант в данном случае — обратиться к разработчику библиотеки.
 
При возникновении дополнительных вопросов, пожалуйста, обращайтесь. Мы будем рады помочь.

**Comment by hcodes** [comment]
Спасибо! Тоже написал, давайте подождём.

**Comment by hcodes** [comment]
v2.2.1
/cc @x100x-dev Проблема должна уйти.

**Comment by x100x-dev** [comment]
Да, спасибо, всё заработало.

x-real-ip поменяли на x-forwarded-for ?

**Comment by hcodes** [comment]
> Да, спасибо, всё заработало.
> 
> x-real-ip поменяли на x-forwarded-for ?

Ага.
