### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by YoyoKarimov** [hcodes/server_yametrika_nodejs#4]
Периодически получаю ошибку:
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }

Проблема в том что в коде:
counter.req(req);
counter.hit();
нет возможности как то поймать данную ошибку.

Есть возможность запускать функцию с callback или любые другие варианты чтобы исправить данную ошибку?

**Comment by hcodes** [comment]
https://github.com/hcodes/server_yametrika_nodejs/blob/master/yametrika.js#L277-L286
req.on('error') нужен?

**Comment by YoyoKarimov** [comment]
Я думаю что да.
У меня стоит в моем коде req.on('error'), но он не ловит данную ошибку.
Но это и понятно, request на метрику идет в другом скопе.

**Comment by hcodes** [comment]
В `settings` нужно пробросить `onError()` и по условию добавить в `_sendData`.
Создатите PR?

**Comment by YoyoKarimov** [comment]
Не уверен что вы это имели ввиду, но pull request создал.

**Comment by YoyoKarimov** [comment]
Есть продвижение по данному вопросу?

**Comment by hcodes** [comment]
Да, щаз запилю.

**Comment by hcodes** [comment]
https://github.com/hcodes/server_yametrika_nodejs/blob/master/yametrika.js#L298
В настройки нужно передать `onerror` для отладки запросов.
v2.1.0

**Comment by YoyoKarimov** [comment]
А не надо было сделать вот так:
if (this._onerror) {
            req.on('error', this._onerror);
            return;
        }

**Comment by hcodes** [comment]
Нет, тогда бы всегда выполнялся `return`.

**Comment by YoyoKarimov** [comment]
К сожалению проблема осталась.
Все так же появляются ошибки.
